In [19]:
import numpy as np
import pandas as pd
import pickle

In [20]:
train_data = pickle.load(open('EDA_Vehicledata.pkl', 'rb'))
train_data

,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Damage_Yes,Annual_Premium,Policy_Sales_Channel,Vintage,Response,Gender,Veh_Age_blw(1-2)_Yrs,Veh_Age_lessthan_1_Yr,Veh_Age_greaterthan_2_Yrs
0,44,1,28.0,0,1,40454.0,26.0,217,1,1,0,0,1
1,76,1,3.0,0,0,33536.0,26.0,183,0,1,1,0,0
2,47,1,28.0,0,1,38294.0,26.0,27,1,1,0,0,1
3,21,1,11.0,1,0,28619.0,152.0,203,0,1,0,1,0
4,29,1,41.0,1,0,27496.0,152.0,39,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
381104,74,1,26.0,1,0,30170.0,26.0,88,0,1,1,0,0
381105,30,1,37.0,1,0,40016.0,152.0,131,0,1,0,1,0
381106,21,1,30.0,1,0,35118.0,160.0,161,0,1,0,1,0
381107,68,1,14.0,0,1,44617.0,124.0,74,0,0,0,0,1
381108,46,1,29.0,0,0,41777.0,26.0,237,0,1,1,0,0

In [21]:
from sklearn.model_selection import train_test_split

train_target=train_data['Response']
train=train_data.drop(['Response'], axis = 1)

X_train,X_test,y_train,y_test = train_test_split(train, train_target, test_size=0.3, random_state = 0)

In [22]:
train_target

0         1
1         0
2         1
3         0
4         0
         ..
381104    0
381105    0
381106    0
381107    0
381108    0
Name: Response, Length: 381109, dtype: int64

In [23]:
train

,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Damage_Yes,Annual_Premium,Policy_Sales_Channel,Vintage,Gender,Veh_Age_blw(1-2)_Yrs,Veh_Age_lessthan_1_Yr,Veh_Age_greaterthan_2_Yrs
0,44,1,28.0,0,1,40454.0,26.0,217,1,0,0,1
1,76,1,3.0,0,0,33536.0,26.0,183,1,1,0,0
2,47,1,28.0,0,1,38294.0,26.0,27,1,0,0,1
3,21,1,11.0,1,0,28619.0,152.0,203,1,0,1,0
4,29,1,41.0,1,0,27496.0,152.0,39,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
381104,74,1,26.0,1,0,30170.0,26.0,88,1,1,0,0
381105,30,1,37.0,1,0,40016.0,152.0,131,1,0,1,0
381106,21,1,30.0,1,0,35118.0,160.0,161,1,0,1,0
381107,68,1,14.0,0,1,44617.0,124.0,74,0,0,0,1
381108,46,1,29.0,0,0,41777.0,26.0,237,1,1,0,0

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [27]:
models = {
    "                   Logistic Regression": LogisticRegression(),
    "                   K-Nearest Neighbors": KNeighborsClassifier(n_neighbors=3),
    "                         Decision Tree": DecisionTreeClassifier(),
    "                         Random Forest": RandomForestClassifier(),
    "Support Vector Machine (Linear Kernel)": LinearSVC(),
    "                        Neural Network": MLPClassifier(),
    "                     Gradient Boosting": GradientBoostingClassifier()
                                   
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(name + " : {:.2f}%".format(accuracy_score(y_pred,y_test)*100))

                   Logistic Regression : 87.67%
                   K-Nearest Neighbors : 84.08%
                         Decision Tree : 82.37%
                         Random Forest : 86.58%

C:\Users\visha\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "

Support Vector Machine (Linear Kernel) : 87.66%

C:\Users\visha\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

                        Neural Network : 87.67%
                     Gradient Boosting : 87.67%

#### 1.LETS BUILD OUR MODEL USING RANDOMFORESTCLASSIFIER:

In [29]:
model=RandomForestClassifier()
model.fit(X_train,y_train)

RandomForestClassifier()

In [30]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,confusion_matrix,r2_score,accuracy_score
from sklearn.metrics import accuracy_score,classification_report

y_pred = model.predict(X_test)

print("Classification Report is:\n",classification_report(y_test,y_pred))
print("Confusion Matrix:\n" , pd.DataFrame(confusion_matrix(y_test,y_pred),columns=['Predicted No','Predicted Yes'],index=['Actual No','Actual Yes']))
print("\nTraining Score: ",model.score(X_test,y_test)*100)
print("\n Mean Squared Error: ",mean_squared_error(y_test,y_pred))
print("\n R2 score is: ",r2_score(y_test,y_pred), "\n")
print(model.get_params())
print("\nAccuracy Score:  ", accuracy_score(y_test,y_pred)*100)

Classification Report is:
               precision    recall  f1-score   support

           0       0.89      0.97      0.93    100241
           1       0.37      0.12      0.18     14092

    accuracy                           0.87    114333
   macro avg       0.63      0.55      0.56    114333
weighted avg       0.82      0.87      0.84    114333

Confusion Matrix:
             Predicted No  Predicted Yes
Actual No          97268           2973
Actual Yes         12357           1735

Training Score:  86.59179764372492

 Mean Squared Error:  0.13408202356275092

 R2 score is:  -0.24078269836908506

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'auto', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False}

Accuracy Score:   86.59179764372492

#### Saving the RandomForest Model:

In [40]:
with open('model_RFC.pkl', 'wb') as f:
    pickle.dump(model, f)

#### 2.LETS BUILD OUR MODEL USING Logistic Regression:

In [41]:
logmodel = LogisticRegression()
logmodel.fit(X_train, y_train)

LogisticRegression()

In [42]:
predictions_ = logmodel.predict(X_test)

In [43]:
from sklearn.metrics import confusion_matrix

In [44]:
accuracy1 = confusion_matrix(y_test, predictions_)

In [45]:
accuracy1

array([[100241,      0],
       [ 14092,      0]], dtype=int64)

In [46]:
from sklearn.metrics import accuracy_score
accuracy_ = accuracy_score(y_test, predictions_)
accuracy_

0.8767459963440126

#### Saving the Logistic Regression model

In [47]:
with open('model_LR.pkl', 'wb') as f:
    pickle.dump(model, f)